// vue/vueshop3.0/src/pages/home/goods/details_item.vue
<template>
  <div class="page">
    <div ref="swpier-wrap" class="swpier-wrap swiper-container">
      <div class="swiper-wrapper">
        <div class="swiper-slide" v-for="(item,index) in details.images" :key="index">
          <img :src="item" alt />
        </div>
      </div>
      <div ref="swiper-pagination" class="swiper-pagination"></div>
    </div>
    <div class="goods-ele-main">
      <div class="goods-title">{{details.title}}</div>
      <div class="price">¥{{details.price}}</div>
      <ul class="sales-wrap">
        <li>快递：{{details.freight}}元</li>
        <li>月销量{{details.sales}}件</li>
      </ul>
    </div>
    <div class="reviews-main">
      <div class="reviews-title">商品评价（{{total}}）</div>
      <div v-show="reviews.length>0">
        <div class="reviews-wrap">
          <div class="reviews-list" v-for="(item,index) in reviews" :key="index">
            <div class="uinfo">
              <div class="head"><img src="../../../assets/images/common/lazyImg.jpg" alt="" :data-echo="item.head"></div>
              <div class="nickname">{{item.nickname}}</div>
            </div>
            <div class="reviews-content" v-html="item.content"></div>
            <div class="reviews-date">{{item.times}}</div>
          </div>
        </div>
        <div class='reviews-more' @click="$router.replace('/goods/details/review?gid='+gid)">查看更多评价</div>
      </div>
      <div class="no-data" v-show="reviews.length<=0">暂无评价！</div>
    </div>
    <div class='bottom-btn-wrap'>
        <div class='btn fav'>收藏</div>
        <div class='btn cart' @click="showPanel()">加入购物车</div>
    </div>
    <div class='mask' v-show="isPanel" @click="hidePanel()"></div>
    <div ref="cart-panel" :class="isPanel ? 'cart-panel up' : 'cart-panel down'">
      <div ref="goods-info" class="goods-info">
        <div class="close-panel-wrap">
          <div class="spot"></div>
          <div class="line"></div>
          <div class="close" @click="hidePanel()"></div>
        </div>
        <div ref="goods-img" class="goods-img">
          <img :src="details.images && details.images[0]" alt="">
        </div>
        <div class="goods-wrap">
          <div class="goods-title">{{details.title}}</div>
          <div class="price">¥{{details.price}}</div>
          <div class="goods-code">商品编码:{{gid}}</div>
        </div>
      </div>
      <div class="attr-wrap">
        <div class="attr-list" v-for="(item,index) in attrs" :key="index">
          <div class="attr-name">{{item.title}}</div>
          <div class="val-wrap">
            <span :class="{'val':true ,'active':item2.active}" v-for="(item2,index2) in item.values" :key="index2" @click="SELECT_ATTR({index:index,index2:index2})">{{item2.value}}</span>
          </div>
        </div>
      </div>
      <div class="amount-wrap">
        <div class="amount-name">购买数量</div>
        <div class="amount-input-wrap">
          <div :class="amount>1?'btn dec':'btn dec active'" @click="amount>1?--amount:1">-</div>
          <div class="amount-input"><input type="tel" :value="amount" @input="setAmount($event)" /></div>
          <div class='btn inc' @click="++amount">+</div>
        </div>
      </div>
      <div class='sure-btn' @click="sureSubmit()">确定</div>
    </div>
  </div>
</template>

<script>
import Vue from "vue";
import { mapState, mapMutations, mapActions } from "vuex";
import Swiper from "../../../assets/js/libs/swiper";

export default {
  data() {
    return {
      isPanel: false,
      amount: 1,
      gid: this.$route.query.gid ? this.$route.query.gid : ""
    };
  },
  created() { 
    this.isMove = true;
    this.getDetails({
      gid: this.gid,
      success: () => {
        this.$nextTick(() => {
          document.title = this.details.title;
          new Swiper(this.$refs["swpier-wrap"], {
            autoplay: 5000, //可选选项，自动滑动
            pagination: this.$refs["swiper-pagination"],
            paginationClickable: true,
            autoplayDisableOnInteraction: false
          });
        });
      }
    });
    this.getReviews({gid:this.gid, success:()=>{
      this.$nextTick(()=>{
        this.$utils.lazyImg();
      })
    }})
  },
  computed: {
    ...mapState({
      attrs: state => state.goods.attrs,
      details: state => state.goods.details,
      total: state => state.goodsReview.total,
      reviews: state => state.goodsReview.reviews
    })
  },
  methods: {
    ...mapMutations({
      SELECT_ATTR: "goods/SELECT_ATTR",
      ADD_ITEM: "cart/ADD_ITEM"
    }),
    ...mapActions({
      getDetails: "goods/getDetails",
      getSpec: "goods/getSpec",
      getReviews: "goodsReview/getReviews"
    }),
    //显示属性面板
    showPanel(){
        this.isPanel=true;
    },
    //隐藏属性面板
    hidePanel(){
        if(this.isMove){
            this.isPanel=false;
        }
    },
    //设置数量
    setAmount(e){
        this.amount=e.target.value;
        this.amount=this.amount.replace(/[^\d]/g,"");
        if(!this.amount || this.amount==="0"){
            this.amount=1;
        }
    },
    sureSubmit() {
      console.log("提交");
    }
  }
};
</script>

<style scoped>
@import "../../../assets/css/common/swiper.css";
.swpier-wrap {
  width: 100%;
  height: 7rem;
  overflow: hidden;
  position: relative;
  z-index: 1;
  margin-top: 1.2rem;
}
.swpier-wrap img {
  width: 100%;
}
.goods-ele-main {
  width: 100%;
  height: auto;
  background-color: #ffffff;
  margin: 0 auto;
  padding-top: 0.5rem;
  padding-bottom: 0.5rem;
}
.goods-ele-main .goods-title {
  width: 90%;
  font-size: 0.28rem;
  margin: 0 auto;
}
.goods-ele-main .price {
  color: #f93036;
  width: 90%;
  margin: 0 auto;
  margin-top: 0.2rem;
  font-size: 0.32rem;
}
.goods-ele-main .sales-wrap {
  width: 90%;
  margin: 0 auto;
  font-size: 0.24rem;
  color: #969696;
  display: flex;
  display: -webkit-flex;
  justify-content: space-between;
  -webkit-justify-content: space-between;
  margin-top: 0.2rem;
}

.reviews-main {
  width: 100%;
  background-color: #ffffff;
  margin-top: 0.5rem;
  overflow: hidden;
  padding-bottom: 1.7rem;
}
.reviews-main .reviews-title {
  color: #7b7f82;
  font-size: 0.32rem;
  width: 90%;
  margin: 0 auto;
  margin-top: 0.2rem;
}
.reviews-main .reviews-wrap {
  width: 90%;
  margin: 0 auto;
}
.reviews-main .reviews-wrap .reviews-list {
  width: 100%;
  margin-top: 0.4rem;
}
.reviews-main .reviews-list .uinfo {
  width: 100%;
  display: flex;
  display: -webkit-flex;
  height: 0.6rem;
  align-items: center;
  -webkit-align-items: center;
}
.reviews-main .reviews-list .uinfo .head {
  width: 0.6rem;
  height: 0.6rem;
  margin-right: 0.2rem;
}
.reviews-main .reviews-list .uinfo .head img {
  width: 100%;
  height: 100%;
  border-radius: 100%;
}
.reviews-main .reviews-list .uinfo .nickname {
  width: auto;
  font-size: 0.28rem;
}
.reviews-main .reviews-list .reviews-content {
  width: 100%;
  margin: 0 auto;
  font-size: 0.28rem;
  margin-top: 0.2rem;
}
.reviews-main .reviews-list .reviews-date {
  width: auto;
  font-size: 0.28rem;
  color: #7b7f82;
  margin-top: 0.2rem;
}
.reviews-main .reviews-more {
  width: 2.44rem;
  height: 0.56rem;
  border: solid 1px #d50a17;
  line-height: 0.56rem;
  text-align: center;
  font-size: 0.28rem;
  margin: 0 auto;
  margin-top: 0.5rem;
  border-radius: 0.1rem;
}

.bottom-btn-wrap {
  width: 100%;
  height: 1.2rem;
  position: fixed;
  bottom: 0px;
  left: 0px;
  z-index: 10;
  display: flex;
  display: -webkit-flex;
}
.bottom-btn-wrap .btn {
  width: auto;
  height: 100%;
  flex: 1;
  -webkit-flex: 1;
  font-size: 0.36rem;
  color: #ffffff;
  text-align: center;
  line-height: 1.2rem;
}
.bottom-btn-wrap .btn.fav {
  background-color: #fcb40a;
}
.bottom-btn-wrap .btn.cart {
  background-color: #cc0004;
}

.mask {
  width: 100%;
  height: 100%;
  position: fixed;
  left: 0px;
  top: 0px;
  z-index: 11;
  background-color: rgba(0, 0, 0, 0.3);
}
.cart-panel {
  width: 100%;
  height: 60%;
  position: fixed;
  z-index: 12;
  left: 0px;
  bottom: 0px;
  background-color: #f5f5f9;
  transition: transform 0.3s;
  -webkit-transition: transform 0.3s;
}
.cart-panel.down {
  transform: translateY(120%);
  -webkit-transform: translateY(120%);
}
.cart-panel.up {
  transform: translateY(0%);
  -webkit-transform: translateY(0%);
}
.cart-panel .goods-info {
  width: 98%;
  height: 1.22rem;
  border-bottom: #efefef solid 1px;
  display: flex;
  display: -webkit-flex;
  align-items: center;
  -webkit-align-items: center;
  padding-left: 0.2rem;
  position: relative;
  z-index: 1;
  background-color: #ffffff;
}
.cart-panel .goods-info .goods-img {
  width: 0.8rem;
  height: 0.8rem;
  margin-right: 0.3rem;
}
.cart-panel .goods-info .goods-img img {
  width: 100%;
  height: 100%;
}
.cart-panel .goods-info .goods-wrap {
  width: 80%;
  height: auto;
}
.cart-panel .goods-info .goods-wrap .goods-title {
  width: 100%;
  height: 0.7rem;
  font-size: 0.24rem;
  overflow: hidden;
}
.cart-panel .goods-info .goods-wrap .price {
  color: #f93036;
  font-size: 0.24rem;
}
.cart-panel .goods-info .goods-wrap .goods-code {
  color: #888888;
  font-size: 0.24rem;
  position: absolute;
  z-index: 1;
  right: 0.2rem;
  bottom: 0px;
}
.cart-panel .close-panel-wrap {
  width: 0.6rem;
  height: 1.2rem;
  position: absolute;
  right: -0.2rem;
  top: -1rem;
  z-index: 2;
}
.cart-panel .close-panel-wrap .spot {
  width: 0.12rem;
  height: 0.12rem;
  position: absolute;
  z-index: 1;
  bottom: 0px;
  left: 0px;
  background-color: #000000;
  border-radius: 100%;
}
.cart-panel .close-panel-wrap .line {
  width: 1px;
  height: 0.72rem;
  background-color: #ffffff;
  position: absolute;
  z-index: 1;
  left: 0.05rem;
  bottom: 0.05rem;
}
.cart-panel .close-panel-wrap .close {
  width: 0.4rem;
  height: 0.4rem;
  background-image: url("../../../assets/images/home/goods/x.png");
  background-size: 100%;
  background-repeat: no-repeat;
  background-position: center;
  position: absolute;
  left: -0.14rem;
  top: 0.1rem;
  z-index: 1;
}

.cart-panel .attr-wrap {
  width: auto;
  max-height: 3.5rem;
  padding-left: 0.2rem;
  background-color: #ffffff;
  overflow-y: scroll;
  overflow-scrolling: touch;
  -webkit-overflow-scrolling: touch;
}
.cart-panel .attr-wrap .attr-list {
  width: 100%;
  height: auto;
  margin-top: 0.2rem;
}
.cart-panel .attr-list .attr-name {
  width: auto;
  font-size: 0.32rem;
}
.cart-panel .attr-list .val-wrap {
  width: auto;
  margin-top: 0.2rem;
  display: flex;
  display: -webkit-flex;
  flex-wrap: wrap;
  -webkit-flex-wrap: wrap;
}
.cart-panel .attr-list .val-wrap .val {
  background: #efefef;
  font-size: 0.32rem;
  padding: 0.1rem 0.2rem;
  border-radius: 0.1rem;
  margin-right: 0.17rem;
  display: table;
  margin-bottom: 0.17rem;
}
.cart-panel .attr-list .val-wrap .val.active {
  color: #ffffff;
  background-color: #fda208;
}

.cart-panel .amount-wrap {
  width: auto;
  padding-left: 0.2rem;
  padding-top: 0.2rem;
  display: flex;
  display: -webkit-flex;
  justify-content: space-between;
  -webkit-justify-content: space-between;
  height: 0.64rem;
  align-items: center;
  -webkit-align-items: center;
  background-color: #ffffff;
  padding-bottom: 0.3rem;
}
.cart-panel .amount-wrap .amount-name {
  width: auto;
  font-size: 0.32rem;
}
.cart-panel .amount-wrap .amount-input-wrap {
  width: 2.04rem;
  height: 0.64rem;
  border: 1px solid #000000;
  margin-right: 0.2rem;
  border-radius: 0.08rem;
  display: flex;
  display: -webkit-flex;
  align-items: center;
  -webkit-align-items: center;
}
.cart-panel .amount-wrap .amount-input-wrap .btn {
  width: 0.6rem;
  height: 0.4rem;
  font-size: 0.32rem;
  text-align: center;
  line-height: 0.4rem;
}
.cart-panel .amount-wrap .amount-input-wrap .btn.active {
  color: #b5b5b5;
}
.cart-panel .amount-wrap .amount-input-wrap .dec {
  border-right: 1px solid #000000;
}
.cart-panel .amount-wrap .amount-input-wrap .amount-input {
  width: 0.76rem;
  height: 100%;
}
.cart-panel .amount-wrap .amount-input-wrap .amount-input input {
  width: 100%;
  height: 95%;
  text-align: center;
}
.cart-panel .amount-wrap .amount-input-wrap .inc {
  border-left: 1px solid #000000;
}
.cart-panel .sure-btn {
  width: 100%;
  height: 0.8rem;
  position: absolute;
  bottom: 0px;
  left: 0px;
  z-index: 1;
  color: #ffffff;
  font-size: 0.32rem;
  background-color: #cf0005;
  text-align: center;
  line-height: 0.8rem;
}
</style>

// react/reactshop2.0/src/pages/home/goods/details_item.js
import React from 'react';
import ReactDOM from 'react-dom';
import {connect} from "react-redux";
import config from '../../../assets/js/conf/config.js';
import {request} from "../../../assets/js/libs/request";
import action from '../../../actions';
import {lazyImg,localParam,setScrollTop} from '../../../assets/js/utils/util.js';
import Swiper from '../../../assets/js/libs/swiper.min.js';
import TweenMax from '../../../assets/js/libs/TweenMax.js';
import { Toast } from 'antd-mobile';
import "../../../assets/css/common/swiper.min.css";
import Css from '../../../assets/css/home/goods/details_item.css';
class DetailsItem extends React.Component{
    constructor(props){
        super(props);
        this.state={
            bMask:false,
            sCartPanel:Css['down'],
            gid:props.location.search!==''?localParam(props.location.search).search.gid:'',
            aAttr: [],
            iAmount:1,
            aSlide:[],
            sGoodsTitle:'',
            fPrice:0,
            fFreight:0,
            iSales:0,
            aReviews:[],
            iReviewTotal:0
        }
        this.bMove=false;
    }
    componentDidMount(){
        setScrollTop();
        this.getGoodsInfo();
        this.getGoodsAttr();
        this.getReviews();
    }
    //获取商品轮番图和获取商品信息
    getGoodsInfo(){
        let sUrl=config.baseUrl+"/home/goods/info?gid="+this.state.gid+"&type=details&token="+config.token;
        request(sUrl).then((res)=>{
            if (res.code ===200){
                this.setState({aSlide:res.data.images,sGoodsTitle:res.data.title,fPrice:res.data.price,fFreight:res.data.freight,iSales:res.data.sales},()=>{
                    new Swiper(this.refs['swpier-wrap'], {
                        autoplay: 3000,
                        pagination : '.swiper-pagination',
                        autoplayDisableOnInteraction : false
                    })
                })
            }
        });
    }
    //获取商品规格属性
    getGoodsAttr(){
        let sUrl=config.baseUrl+"/home/goods/info?gid="+this.state.gid+"&type=spec&token="+config.token;
        request(sUrl).then(res=>{
            if (res.code===200){
                this.setState({aAttr:res.data});
            }
        });
    }
    //获取商品评价
    getReviews(){
        let sUrl=config.baseUrl+"/home/reviews/index?gid="+this.state.gid+"&token="+config.token+"&page=1";
        request(sUrl).then((res)=>{
            if (res.code===200){
                this.setState({aReviews:res.data, iReviewTotal:res.pageinfo.total},()=>{
                    lazyImg();
                });
            }else{
                this.setState({aReviews:[]})
            }
        });
    }
    //显示购物控制面板
    showCartPanel(){
        this.refs['mask'].addEventListener("touchmove",function (e) {
            e.preventDefault();
        },false);
        this.setState({sCartPanel:Css['up'],bMask:true});
    }
    //隐藏购物控制面板
    hideCartPanel(){
        if (!this.bMove){
            this.setState({sCartPanel:Css['down'],bMask:false});
        }
    }
    //加入收藏
    addFav(){
        if (this.props.state.user.isLogin){
            let url=config.baseUrl+"/goods/fav?uid="+this.props.state.user.uid+"&gid="+this.state.gid+"&token="+config.token;
            request(url).then(res=>{
                Toast.info(res.data, 2);
            });
        }else{
            Toast.info('请登录会员', 2);
        }

    }
    replacePage(url){
        this.props.history.replace(config.path+url);
    }
    //选择属性值
    selectAttrVal(attrIndex,valIndex){
        let aAttr=this.state.aAttr;
        if (aAttr.length>0){
            for (let key in aAttr[attrIndex].values){
                aAttr[attrIndex].values[key].checked=false;
            }
        }
        aAttr[attrIndex].values[valIndex].checked=true;
        this.setState({aAttr:aAttr});
    }
    //增加数量
    incAmount(){
        let iAmount=this.state.iAmount;
        this.setState({iAmount:++iAmount});
    }
    //减少数量
    decAmount(){
        let iAmount=this.state.iAmount;
        if (iAmount>1){
            this.setState({iAmount:--iAmount});
        }
    }
    //加入购物车
    addCart(){
        this.checkAttrVal(()=>{
            if (!this.bMove){
                this.bMove = true;
                let oGoodsImg=this.refs['goods-img'],oGoodsInfo=this.refs['goods-info'],oCartPanel=this.refs['cart-panel'];
                let oCartIcon=ReactDOM.findDOMNode(document.getElementById("cart-icon"));
                let oCloneImg=oGoodsImg.cloneNode(true);
                oGoodsInfo.appendChild(oCloneImg);
                oCloneImg.style.cssText="width:0.4rem;height:0.4rem;position:absolute;z-index:1;left:0.2rem;top:0.2rem;";
                let srcImgX=oGoodsImg.offsetLeft;
                let cloneY=parseInt(window.innerHeight-oCartPanel.offsetHeight+oGoodsImg.offsetTop-oCartIcon.offsetTop);
                TweenMax.to(oCloneImg, 2, {bezier:[{x:srcImgX, y:-100},{x:srcImgX+30, y:-130},{x:oCartIcon.offsetLeft, y:-cloneY}],onComplete:()=>{
                        oCloneImg.remove();
                        this.bMove=false;

                        //将商品添加到redux
                        let aAttr=[],aParam=[];
                        if (this.state.aAttr.length>0){
                            for (let key in this.state.aAttr){
                                if (this.state.aAttr[key].values.length>0){
                                    aParam=[];
                                    for (let key2 in this.state.aAttr[key].values){
                                        if (this.state.aAttr[key].values[key2].checked){
                                            aParam.push({paramid:this.state.aAttr[key].values[key2].vid,title:this.state.aAttr[key].values[key2].value})
                                        }
                                    }
                                }
                                aAttr.push({attrid:this.state.aAttr[key].attrid, title:this.state.aAttr[key].title,param:aParam});
                            }
                        }
                        this.props.dispatch(action.cart.addCart({gid:this.state.gid,title:this.state.sGoodsTitle,amount:parseInt(this.state.iAmount),price:this.state.fPrice,img:this.state.aSlide[0],checked:true,freight:this.state.fFreight,attrs:aAttr}))
                    }});
                TweenMax.to(oCloneImg,0.2,{rotation:360,repeat:-1});
            }
        });
    }
    //检测是否选择属性值
    checkAttrVal(callback){
        let aAttr=this.state.aAttr,bSelect=false,attrName='';
        if (aAttr.length>0){
            for (let key in aAttr){
                bSelect=false;
                for (let key2 in aAttr[key].values){
                    if (aAttr[key].values[key2].checked){
                        bSelect=true;
                        break;
                    }
                }
                if (!bSelect){
                    attrName=aAttr[key].title;
                    break;
                }
            }
            if (!bSelect){
                Toast.info(`请选择${attrName}`,2);
            }
            if (bSelect){
                callback()
            }
        }
    }
    componentWillUnmount(){
        this.setState=(state,callback)=>{
            return;
        }
    }
    //更改商品数量
    changeAmount(e){
        let iAmount=1;
        if (e.target.value!==''){
            iAmount = e.target.value.replace(/[a-zA-Z]|[\u4e00-\u9fa5]|[#|*|,|+|;|.]/g,'');
            if (iAmount===''){
                iAmount=1;
            }
        }
        this.setState({iAmount:iAmount});
    }
    render(){
        return(
            <div>
                <div ref="swpier-wrap" className={Css['swpier-wrap']}>
                    <div className="swiper-wrapper">
                        {
                            this.state.aSlide.length>0?
                                this.state.aSlide.map((item, index)=>{
                                    return (
                                        <div className="swiper-slide" key={index}><img src={item} alt={this.state.sGoodsTitle} /></div>
                                    )
                                })
                            :''
                        }
                    </div>
                    <div className="swiper-pagination"></div>
                </div>
                <div className={Css['goods-ele-main']}>
                    <div className={Css['goods-title']}>{this.state.sGoodsTitle}</div>
                    <div className={Css['price']}>¥{this.state.fPrice}</div>
                    <ul className={Css['sales-wrap']}>
                        <li>快递：{this.state.fFreight}元</li>
                        <li>月销量{this.state.iSales}件</li>
                    </ul>
                </div>
                <div className={Css['reviews-main']}>
                    <div className={Css["reviews-title"]}>商品评价（{this.state.iReviewTotal}）</div>
                    <div className={Css['reviews-wrap']}>
                        {
                            this.state.aReviews.length>0?
                                this.state.aReviews.map((item, index)=>{
                                    return (
                                        <div className={Css['reviews-list']} key={index}>
                                            <div className={Css['uinfo']}>
                                                <div className={Css['head']}><img alt={item.nickname} data-echo={item.head} src={require("../../../assets/images/common/lazyImg.jpg")}  /></div>
                                                <div className={Css['nickname']}>{item.nickname}</div>
                                            </div>
                                            <div className={Css['reviews-content']}>{item.content}</div>
                                            <div className={Css['reviews-date']}>{item.times}</div>
                                        </div>
                                    )
                                })
                            :<div className="null-item">没有任何评价！</div>
                        }
                    </div>
                    <div className={this.state.iReviewTotal>0?Css['reviews-more']:Css['reviews-more']+" hide"} onClick={this.replacePage.bind(this, 'goods/details/reviews?gid='+this.state.gid)}>查看更多评价</div>
                </div>
                <div className={Css['bottom-btn-wrap']}>
                    <div className={Css['btn']+" "+Css['fav']} onClick={this.addFav.bind(this)}>收藏</div>
                    <div className={Css['btn']+" "+Css['cart']} onClick={this.showCartPanel.bind(this)}>加入购物车</div>
                </div>
                <div ref="mask" className={this.state.bMask?Css['mask']:Css['mask']+" hide"}></div>
                <div ref="cart-panel" className={Css['cart-panel']+" "+this.state.sCartPanel}>
                    <div ref="goods-info" className={Css['goods-info']}>
                        <div className={Css['close-panel-wrap']}>
                            <div className={Css['spot']}></div>
                            <div className={Css["line"]}></div>
                            <div className={Css['close']} onClick={this.hideCartPanel.bind(this)}></div>
                        </div>
                        <div ref="goods-img" className={Css['goods-img']}>
                            <img src={this.state.aSlide.length!==0?this.state.aSlide[0]:''} alt={this.state.sGoodsTitle} />
                        </div>
                        <div className={Css['goods-wrap']}>
                            <div className={Css['goods-title']}>{this.state.sGoodsTitle}</div>
                            <div className={Css['price']}>¥{this.state.fPrice}</div>
                            <div className={Css['goods-code']}>商品编码:{this.state.gid}</div>
                        </div>
                    </div>
                    <div className={Css['attr-wrap']}>
                        {
                            this.state.aAttr.length>0?
                                this.state.aAttr.map((item,index)=>{
                                    return (
                                        <div className={Css['attr-list']} key={index}>
                                            <div className={Css['attr-name']}>{item.title}</div>
                                            <div className={Css['val-wrap']}>
                                                {
                                                    item.values.length>0?
                                                        item.values.map((item2,index2)=>{
                                                            return (
                                                                <span key={index2} className={item2.checked?Css['val']+" "+Css['active']:Css['val']} onClick={this.selectAttrVal.bind(this,index, index2)}>{item2.value}</span>
                                                            )
                                                        })
                                                    :''
                                                }
                                            </div>
                                        </div>
                                    )
                                })
                            :''
                        }
                    </div>
                    <div className={Css['amount-wrap']}>
                        <div className={Css['amount-name']}>购买数量</div>
                        <div className={Css["amount-input-wrap"]}>
                            <div className={this.state.iAmount<=1?Css['btn']+" "+Css['dec']+" "+Css["active"]:Css['btn']+" "+Css['dec']} onClick={this.decAmount.bind(this)}>-</div>
                            <div className={Css['amount-input']}><input type="tel" value={this.state.iAmount} onChange={(e)=>{this.changeAmount(e)}}/></div>
                            <div className={Css['btn']+" "+Css['inc']} onClick={this.incAmount.bind(this)}>+</div>
                        </div>
                    </div>
                    <div className={Css['sure-btn']} onClick={this.addCart.bind(this)}>确定</div>
                </div>
            </div>
        );
    }
}
export default connect((state)=>{
    return{
        state:state
    }
})(DetailsItem)
