// react/reactshop2.0/src/pages/home/goods/classify.js
import React from 'react';
import  {Route,Switch}  from  'react-router-dom';
import asyncComponents from '../../../components/async/AsyncComponent';
import config from '../../../assets/js/conf/config.js';
import IScroll from '../../../assets/js/libs/iscroll.js';
import Css from '../../../assets/css/home/goods/classify.css';
import {request} from "../../../assets/js/libs/request";
import {localParam,isSystem,setScrollTop} from "../../../assets/js/utils/util";
import SearchComponent from '../../../components/search/search';
const GoodsItems=asyncComponents(()=>import('./items'));
export default class  GoodsClassify extends React.Component{
    constructor(props){
        super(props);
        this.state={
            aClassify:[],
            pageStyle:{display:"none"}
        };
        this.myScroll=null;
        this.aTempClassify=[];
        this.cid=props.location.search?localParam(props.location.search).search.cid:'492';
    }
    componentDidMount(){
        setScrollTop()
        this.getClassifyData();
    }
    replacePage(pUrl){
      this.props.history.replace(config.path+pUrl);
    }
    goBack(){
        this.props.history.goBack();
    }
    eventScroll(){
        let scrollClassify=this.refs["scroll-classify"];
        scrollClassify.addEventListener('touchmove', function (e) { e.preventDefault(); }, false);
        this.myScroll= new IScroll(scrollClassify, {
            scrollX : false,
            scrollY : true,
            preventDefault : false
        });
    }
    getClassifyData(){
        request(config.baseUrl+"/home/category/menu?token="+config.token).then(res =>{
            if (res.code ===200){
                this.aTempClassify=res.data;
                for (let i=0;i<this.aTempClassify.length;i++){
                    this.aTempClassify[i].bActive=false;
                }
                this.setState({aClassify:this.aTempClassify},()=>{
                    this.eventScroll();
                    this.defaultClassifyStyle();
                })
            }
        } );
    }
    changeStyle(pUrl,pIndex){
        if (this.aTempClassify.length>0){
            for (let i=0;i<this.aTempClassify.length;i++){
                this.aTempClassify[i].bActive=false;
            }
        }
        this.aTempClassify[pIndex].bActive=true;
        this.handleScroll(pIndex);
        this.replacePage(pUrl);
    }
    handleScroll(pIndex){
        let oScrollClassify=this.refs["scroll-classify"];
        let iTopHeight=Math.round(parseInt(this.refs['item-'+pIndex].offsetHeight)*pIndex);
        let iHalfHeight=Math.round(oScrollClassify.offsetHeight/3);
        let iBottomHeight=oScrollClassify.scrollHeight-iTopHeight;
        if (iTopHeight>iHalfHeight && iBottomHeight>oScrollClassify.offsetHeight){
            this.myScroll.scrollTo(0,-iTopHeight,300,IScroll.utils.ease.elastic);
        }
    }
    defaultClassifyStyle(){
        if (this.aTempClassify.length>0){
            for (let i=0;i<this.aTempClassify.length;i++){
                if (this.aTempClassify[i].cid ===this.cid){
                    this.aTempClassify[i].bActive=true;
                    break;
                }
            }
            this.setState({aClassify:this.aTempClassify});
        }
    }
    getStyle(val){
        this.setState({pageStyle:val})
    }
    changeSearch(){
        this.setState({pageStyle:{display:"block"}})
    }
    componentWillUnmount(){
        this.setState=(state,callback)=>{
            return;
        }
    }
    render(){
        return(
            <div>
                <div className={Css['search-header']}>
                    <div className={Css['back']} onClick={this.goBack.bind(this)}></div>
                    <div className={Css['search']} onClick={this.changeSearch.bind(this)}>请输入宝贝名称</div>
                </div>
                <div className={Css['goods-main']}>
                    <div ref="scroll-classify" className={Css['classify-wrap']}>
                        <div>
                            {
                                this.state.aClassify!=null?
                                    this.state.aClassify.map((item, index)=>{
                                        return(
                                            <div ref={"item-"+index} className={item.bActive?Css['classify-item']+" "+Css['active']:Css['classify-item']} key={index} onClick={this.changeStyle.bind(this, 'goods/classify/items?cid='+item.cid+'',index)}>{item.title}</div>
                                        )
                                    })
                                :""
                            }
                            {
                                isSystem()===1?<div style={{width:'100%',height:'1.6rem'}}></div>:<div style={{width:'100%',height:'0.8rem'}}></div>
                            }
                        </div>
                    </div>
                    <div className={Css['goods-content']}>
                        <Switch>
                            <Route path={config.path+"goods/classify/items"} component={GoodsItems}></Route>
                        </Switch>
                    </div>
                </div>
                <SearchComponent pageStyle={this.state.pageStyle} childStyle={this.getStyle.bind(this)}></SearchComponent>
            </div>
        );
    }
}

// vue/vueshop3.0/src/pages/home/goods/classify.vue
<template>
    <div class="page">
        <div class="search-header" @click="searchShow.show=true">
            <div class="back" @click="goBack()"></div>
            <div class="search">请输入宝贝名称</div>
        </div>
        <div class="goods-main">
            <div ref="scroll-classify" class="classify-wrap">
                <div>
                    <div ref="item" :class="{'classify-item':true, active:item.active}" v-for="(item,index) in classifys" :key="index" @click="replacePage('/goods/classify/item?cid='+item.cid+'',index)">{{item.title}}</div>
                </div>
            </div>
            <div class="goods-content">
                <router-view></router-view>
            </div>
        </div>
        <my-search :show="searchShow"></my-search>
    </div>
</template>

<script>
import {mapState, mapActions,mapMutations} from 'vuex';
import IScroll from '../../../assets/js/libs/iscroll';
import MySearch from '../../../components/search';
export default {
    name:"classify",
    data() {
        return {
            searchShow:{show:false}
        }
    },
    components:{
        MySearch
    },
    computed:{
        ...mapState({
            classifys:state=>state.goods.classifys,
        })
    },
    methods:{
        ...mapActions({
            getClassify:"goods/getClassify"
        }),
        ...mapMutations({
            SELECT_ITEM:"goods/SELECT_ITEM"
        }),
        goBack() {
            this.$router.go(-1);
        },
        scrollPreventDefault(e){
            e.preventDefault();
        },
        selectItem(index) {
            let topHeight = this.$refs['item'][0].offsetHeight*index;
            // console.log(this.$refs['item'])
            let halfHeight = parseInt(this.$refs['scroll-classify'].offsetHeight/3);
            let bottomHeight = parseInt(this.$refs['scroll-classify'].scrollHeight-topHeight);
            if(topHeight > halfHeight && bottomHeight > this.$refs['scroll-classify'].offsetHeight) {
                this.myScroll.scrollTo(0,-topHeight,1000,IScroll.utils.ease.elastic);
            }
            this.SELECT_ITEM({index:index});
        },
        replacePage(url, index) {
            this.$router.replace(url);
            this.selectItem(index);
        }
    },
    created() {
        this.cid = this.$route.query.cid ? this.$route.query.cid : '';
        this.getClassify({success:()=>{
            this.$nextTick(()=>{
                this.myScroll.refresh();
                if(this.classifys.length > 0 && this.cid) {
                    let i = 0;
                    for(; i < this.classifys.length; i++ ){
                        if(this.classifys[i].cid === this.cid) {
                            break;
                        }
                    }
                    this.selectItem(i);
                }else{
                    this.selectItem(0);
                }
            })
        }})
    },
    mounted() {
        document.title = this.$route.meta.title;
        this.$refs['scroll-classify'].addEventListener("touchmove",this.scrollPreventDefault);
        this.myScroll = new IScroll(this.$refs['scroll-classify'], {
            scrollX: false,
            scrollY: true,
            preventDefault: false
        });
    },
    beforeDestroy() {
        this.$refs['scroll-classify'].removeEventListener("touchmove",this.scrollPreventDefault);
    }
}
</script>

<style scoped>
    .page{width: 100%;height: 100vh;overflow: hidden;}
    .search-header{width: 100%;height: 1rem;background-color: #ffffff;display: flex;display: -webkit-flex;align-items: center;-webkit-align-items: center;border-bottom: 1px solid #EFEFEF;}
    .search-header .back{width:0.8rem;height:0.8rem;background-image: url("../../../assets/images/home/goods/back.png");background-size:100%;background-repeat: no-repeat;background-position: center;}
    .search-header .search{width:80%;height:0.69rem;border:solid 1px #B2B2B2;border-radius: 0.1rem;font-size:0.28rem;color:#626262;line-height:0.69rem;padding-left:0.2rem;}

    .goods-main{width:100%;height:92.5vh;display:flex;display:-webkit-flex;}
    .goods-main .classify-wrap{width:1.72rem;height:100%;overflow:hidden;margin-right:3%;position:relative;z-index:1;}
    .goods-main .classify-wrap .classify-item{width:100%;height:0.8rem;border-bottom: 1px solid #EFEFEF;background-color:#FFFFFF;font-size:0.28rem;text-align: center;line-height:0.8rem;overflow:hidden;}
    .goods-main .classify-wrap .classify-item.active{color:#ff0000}
    .goods-main .goods-content{width:71%;height:100%;}
</style>
